title: dadda.moe
author:
  name: Dadda aka Flo
  email: post [at] dadda [dot] moe
description: >
  Ich bin ein Mensch wie du, er/ihm, der versucht Inhalte zu produzieren, welche Besucher dieser Seite lesenswert finden. Wie fast alles was ich tue, widme ich diese Seite meinen beiden wundervollen Töchtern und meiner Partnerin. Danke dass ihr die Sonne in mein Nerd-Herz scheinen lasst. ♥️
open-source: >
  Diese Website wurde mit Open Source Technologie wie Jekyll, Mermaid und VS Codium entwickelt. Ich möchte den Entwickler:innen für ihre großartige Software danken.
tracking-info: >
  Diese Seite ist frei von Tracking.
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag


# Theme-specific settings

minima:
  date_format: "%Y-%m-%d"
  social_links:
  - { platform: github,   user_url: "https://github.com/flowinho" }
  - { platform: mastodon, user_url: "https://chaos.social/@flowinho" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
<<<<<<< HEAD
  - _pages/mtg-wishlist.md
=======
  #- impressum.md
  #- datenschutz.md
  - mtg-wishlist.md
>>>>>>> parent of a04c421 (Change folder-structure)

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
