title: dadda.moe
author:
  name: Dadda aka Flo
  email: post [at] dadda [dot] moe
description: >
  Ein einfacher Mensch, er/ihm, der versucht Inhalte zu produzieren, die Besicher dieser Seite hoffentlich lesenswert finden. Wie fast alles was ich tue, widme ich diese Seite meinen beiden wundervollen Töchtern und meiner Partnerin. Danke dass ihr die Sonne in mein Nerd-Herz scheinen lasst. ♥️

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  date_format: "%Y-%m-%d"
  social_links:
  - { platform: github,         user_url: "https://github.com/flowinho" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
